### ISSUE TITLE
Nextcloud News setup

### ISSUE THREAD

**Issue by retarepo** [matztam/ARD-Audiothek-RSS#8]
Hello,

thanks for the really awesome script. I just wanted to share here my experience with including it to my nextcloud docker-compose setup:
```yaml
services:
  ...
  ardaudiothek:
    build:
      context: ./ardaudiothek-rss
      dockerfile: Dockerfile

  nextcloud:
    ....
```
since both or in the same "default" network, the nextcloud instance can access it without exposing it publicly. Just the URLs change a bit, in my case to `http://ardaudiothek/?show=1234567890`

best wishes
